name: GitHub Actions Linked Video
run-name: ${{ github.actor }} ${{ github.repository }} Actions 🚀

on: [push]
jobs:
  BuildTest:
    uses: ./.github/workflows/build-and-test.yml
    with:
      stage: 'dev'
    secrets: inherit

  JobStatus:
    name: Next
    needs: [BuildTest]
    runs-on: ubuntu-latest
    steps:
      - run: echo job status ${{ job.status }}
    